apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: nacf
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: nacf
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka
  namespace: nacf
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: message-queue
    app.kubernetes.io/part-of: nacf
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zookeeper
  namespace: nacf
  labels:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/component: coordination
    app.kubernetes.io/part-of: nacf
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  namespace: nacf
  labels:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/component: authentication
    app.kubernetes.io/part-of: nacf
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: signal-processor
  namespace: nacf
  labels:
    app.kubernetes.io/name: signal-processor
    app.kubernetes.io/component: processing
    app.kubernetes.io/part-of: nacf
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: model-inference
  namespace: nacf
  labels:
    app.kubernetes.io/name: model-inference
    app.kubernetes.io/component: inference
    app.kubernetes.io/part-of: nacf