apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/component: coordination
    app.kubernetes.io/part-of: nacf
spec:
  ports:
  - port: 2181
    targetPort: 2181
    name: client
  clusterIP: None
  selector:
    app.kubernetes.io/name: zookeeper