apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
    app.kubernetes.io/part-of: nacf
spec:
  ports:
  - name: redis
    port: 6379
    targetPort: redis
    protocol: TCP
  clusterIP: None
  selector:
    app.kubernetes.io/name: redis
  type: ClusterIP
