apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/component: message-queue
    app.kubernetes.io/part-of: nacf
spec:
  ports:
  - port: 9092
    targetPort: 9092
    name: kafka
  - port: 29092
    targetPort: 29092
    name: kafka-internal
  clusterIP: None
  selector:
    app.kubernetes.io/name: kafka