apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  labels:
    app.kubernetes.io/name: kong
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/part-of: nacf
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: kong
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kong
        app.kubernetes.io/component: api-gateway
        app.kubernetes.io/part-of: nacf
    spec:
      containers:
      - name: kong
        image: kong:3.0
        env:
          - name: KONG_PROXY_ACCESS_LOG
            value: /dev/stdout
          - name: KONG_ADMIN_ACCESS_LOG
            value: /dev/stdout
          - name: KONG_PROXY_ERROR_LOG
            value: /dev/stderr
          - name: KONG_ADMIN_ERROR_LOG
            value: /dev/stderr
          - name: KONG_ADMIN_LISTEN
            value: 0.0.0.0:8001, 0.0.0.0:8444 ssl
          - name: KONG_DATABASE
            value: "off"
          - name: KONG_DECLARATIVE_CONFIG
            value: /etc/kong/kong.yml
          - name: KONG_PROXY_LISTEN
            value: 0.0.0.0:8000, 0.0.0.0:8443 ssl
        ports:
        - containerPort: 8000
          name: proxy
          protocol: TCP
        - containerPort: 8443
          name: proxy-ssl
          protocol: TCP
        - containerPort: 8001
          name: admin
          protocol: TCP
        - containerPort: 8444
          name: admin-ssl
          protocol: TCP
        volumeMounts:
        - name: kong-config
          mountPath: /etc/kong/
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /status
            port: admin
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /status
            port: admin
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
      volumes:
      - name: kong-config
        configMap:
          name: kong-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-config
data:
  kong.yml: |
    _format_version: "2.1"
    _transform: true
    services:
      - name: auth-service
        url: http://auth-service.nacf.svc.cluster.local
        routes:
          - name: auth-api
            paths:
              - /api/v1/auth
            methods: ["GET", "POST"]
            strip_path: false
        plugins:
          - name: rate-limiting
            config:
              minute: 100
              hour: 1000
              policy: local
          - name: key-auth
            enabled: true
            config:
              key_names: ["apikey"]
              hide_credentials: true

      - name: signal-processor
        url: http://signal-processor.nacf.svc.cluster.local
        routes:
          - name: signal-api
            paths:
              - /api/v1/process
            methods: ["POST"]
            strip_path: false
        plugins:
          - name: request-size-limiting
            config:
              allowed_payload_size: 10
          - name: key-auth
            enabled: true
            config:
              key_names: ["apikey"]
              hide_credentials: true
---
apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  labels:
    app.kubernetes.io/name: kong
    app.kubernetes.io/component: api-gateway
    app.kubernetes.io/part-of: nacf
spec:
  type: LoadBalancer
  ports:
  - name: proxy
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: proxy-ssl
    port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    app.kubernetes.io/name: kong
