apiVersion: v1
kind: Service
metadata:
  name: model-inference
  labels:
    app.kubernetes.io/name: model-inference
    app.kubernetes.io/component: inference
    app.kubernetes.io/part-of: nacf
spec:
  ports:
  - port: 8001
    targetPort: 8001
    name: http
  selector:
    app.kubernetes.io/name: model-inference
  type: ClusterIP